replication:
  connections:
    - type: postgresql
      uri: !env PS_SOURCE_URI
      sslmode: disable

storage:
  type: postgresql
  uri: !env PS_STORAGE_URI
  sslmode: disable

port: 8080

client_auth:
  audience:
    - !env PS_JWT_AUDIENCE
  jwks:
    keys:
      - kty: oct
        alg: HS256
        kid: !env PS_JWT_KID
        k: !env PS_JWT_SECRET_B64URL

sync_rules:
  content: |
    bucket_definitions:
      demo_data:
        data:
          - SELECT * FROM app_user
          - SELECT * FROM ticket
          - SELECT * FROM ticket_assignment
          - SELECT * FROM ticket_comment
          - SELECT * FROM ticket_attachment_url
          - SELECT * FROM ticket_link
          - SELECT * FROM ticket_description_update
          - SELECT * FROM ticket_conflict
          - SELECT * FROM ticket_activity
